@startuml
left to right direction

actor Visiteur
actor Utilisateur

rectangle "Système de vente de formations" {

 usecase "Se connecter" as AUTH

 usecase "Consulter les formations" as UC1
 usecase "Rechercher des formations" as UC2

 usecase "Créer un compte" as UC3

 usecase "Gérer le panier" as UC5
 usecase "Passer commande" as UC6
 usecase "Consulter mes commandes" as UC7

}

Visiteur -- UC1
Visiteur -- UC2
Visiteur -- UC3

Utilisateur -|> Visiteur

Utilisateur -- UC5
Utilisateur -- UC6
Utilisateur -- UC7

UC5 ..> AUTH : <<include>>
UC6 ..> AUTH : <<include>>
UC7 ..> AUTH : <<include>>

@enduml
